# Generated by Django 5.2.8 on 2025-11-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_subcategory'),
        ('store', '0003_alter_subcategory_category'),
    ]

    operations = [
    ]
